package org.aryalinux.projectbuilder;

import java.io.BufferedReader;
import java.io.InputStreamReader;

public class Property {
	private String name;
	private String label;
	private String javaDataType;
	private String dbDataType;
	private boolean isPrimaryKey;
	private boolean isAutogenerated;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isPrimaryKey() {
		return isPrimaryKey;
	}

	public void setPrimaryKey(boolean isPrimaryKey) {
		this.isPrimaryKey = isPrimaryKey;
	}

	public boolean isAutogenerated() {
		return isAutogenerated;
	}

	public void setAutogenerated(boolean isAutogenerated) {
		this.isAutogenerated = isAutogenerated;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getJavaDataType() {
		return javaDataType;
	}

	public void setJavaDataType(String javaDataType) {
		this.javaDataType = javaDataType;
	}

	public String getDbDataType() {
		return dbDataType;
	}

	public void setDbDataType(String dbDataType) {
		this.dbDataType = dbDataType;
	}

	public void readFromConsole() {
		System.out.println("Please enter all these details, separated by commas for the property: ");
		System.out.println("Name, Label, Java data type, Database data type, Is primary, Is autogenerated");
		try {
			BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));
			String line = bufferedReader.readLine();
			String[] parts = line.split(",");
			setName(parts[0]);
			setLabel(parts[1]);
			setJavaDataType(parts[2]);
			setDbDataType(parts[3]);
			if (parts[4] != "") {
				setPrimaryKey(Boolean.parseBoolean(parts[4]));
			} else {
				setPrimaryKey(false);
			}
			if (parts[5] != "") {
				setAutogenerated(Boolean.parseBoolean(parts[5]));
			} else {
				setAutogenerated(false);
			}
		} catch (Exception ex) {
			throw new RuntimeException(ex);
		}
	}
}
